#!/usr/bin/env python3
import sys, io

if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

print("=== 손실 원인 분석 ===\n")

print("1. 수수료 문제")
print("=" * 50)
print("- 업비트 거래 수수료: 0.05%")
print("- OKX 거래 수수료: 0.1% (Taker)")
print("- 왕복 수수료: 0.3%")
print("- 슬리피지 + 가격 변동: 0.1~0.2%")
print("- 실제 필요 차익: 0.4~0.5% 이상")
print("- 우리 설정: 0.6% → 이론상 0.1~0.2% 수익")
print()

print("2. 거래 실패 패턴")
print("=" * 50)
print("문제: OKX 매수 성공 → 업비트 매도 실패")
print()
print("발생 케이스:")
print("- OKX에서 ID 매수 (예: 143개)")
print("- 업비트에서 ID 매도 시도")
print("- 매도 실패 (오류: unsupported format string)")
print("- 결과: OKX에 ID만 쌓임")
print()
print("누적 효과:")
print("- 1회: OKX ID +143개")
print("- 2회: OKX ID +150개")
print("- 3회: OKX ID +1147개 (여러 번 반복)")
print("- 매번 OKX ID 매도 시 손실 (매수가보다 낮은 가격)")
print()

print("3. 수량 불일치")
print("=" * 50)
print("- OKX에서 $6 매수 → 약 145개 받음")
print("- 업비트에서 141개 매도 시도 (수량 감소)")
print("- 반복하면 업비트 ID 고갈")
print("- 업비트 ID 부족 → OKX만 계속 매수")
print()

print("4. 한 코인 집중")
print("=" * 50)
print("- ID만 반복 거래 (BAT, ALGO는 거래 안 함)")
print("- ID 차익이 사라지면 거래 중단")
print("- 다른 코인 기회 놓침")
print()

print("5. 매도 오류 원인")
print("=" * 50)
print("코드 문제:")
print("  sell = upbit.create_market_sell_order(f'{coin}/KRW', sell_qty)")
print("  krw_got = sell.get('cost', 0)")
print()
print("- sell 객체가 None이거나 cost 필드 없음")
print("- 오류 발생 시 except로 넘어감")
print("- 하지만 OKX 매수는 이미 완료됨")
print()

print("6. 실제 손실 계산")
print("=" * 50)
print("시작: 118,308원")
print("현재: 110,000원")
print("손실: -8,308원 (7% 손실)")
print()
print("손실 구성:")
print("- 수수료 누적: 약 -3,000원 (20회 거래 × 150원)")
print("- OKX ID 매도 시 손실: 약 -5,000원 (매수 후 가격 하락)")
print("- 슬리피지: 약 -300원")
print()

print("결론")
print("=" * 50)
print("1. 매수/매도가 동시에 성공하지 않음")
print("2. 한쪽만 거래되어 코인이 쌓임")
print("3. 쌓인 코인을 손실 가격에 매도")
print("4. 수수료가 예상보다 많이 발생")
print("5. 거래 로직의 원자성(atomicity) 부재")
